---
output:
  html_document:
    toc: false
editor_options: 
  chunk_output_type: console
---

## Домашнее задание (до 19.12.2018)

* Обязательно:
    * [Introduction to attractor landscapes](https://ncase.me/attractors/) (занимает минут 5)
    * Вспомнить, перемножение матриц и что такое [собственные векторы](https://ru.wikipedia.org/wiki/%D0%A1%D0%BE%D0%B1%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80)
* По желанию:
    * [The evolution of trust](https://ncase.me/trust/) (занимает минут 30)
    * [The wisdom and/or madness of crowds](https://ncase.me/crowds/) (занимает минут 30)
    * я открыл в этом году издание [Pudding](https://pudding.cool/), там выходят статьи с красивой интерактивной визуализацией, основанной на реальных данных. Будет настроение --- взгляните.

## Домашнее задание (до 26.12.2018)
Домашнее задание нужно выполнять в отдельном `rmarkdown` файле. Получившийся файл следует помещать в соответствующую папку в своем репозитории на гитхабе. Более подробные инструкции [см. на этой странице](https://agricolamz.github.io/2018_data_analysis_for_linguists/index.html).

В этой домашней работе я предлагаю поработать с поддатасетом данных из базы данных [Phoible](https://phoible.org/), в которой собраны фонологические инвентари в языках мира. В каждый набор данных записано всего три переменных:

* `language` --- язык;
* `consonants` --- количество согласных;
* `phonemes` --- количество фонем.

Я предлагаю исследовать долю, которую согласные составляют от всего фонологического набора.

### 2.1
Посчитайте долю, которую составляет согласные от всего фонологического набора каждого языка и выведите в консоль название языка, в котором эта доля максимальна

### 2.2
На основании среднего и стандартного отклонения долей, представленных в Вашем датасете, оцените параметр α бета-распределения и выведите его в консоль.

### 2.3
На основании среднего и стандартного отклонения долей, представленных в Вашем датасете, оцените параметр β бета-распределения и выведите его в консоль.

### 2.4
Проведите байесовский апдейт наблюдений каждого языка, используя бета распределение с параметрами α и β, полученные в предыдущих заданиях. Посчитайте модуль разницы между апостериорной долей и изночальной долей представленной в данных. В консоль выведите 6 языков с наибольшей разницей.

