---
output:
  html_document:
    toc: false
editor_options: 
  chunk_output_type: console
---

## Домашнее задание (до 22.01.2019)

* Обязательно:
    * [Introduction to attractor landscapes](https://ncase.me/attractors/) (занимает минут 5)
    * Вспомнить, перемножение матриц и что такое [собственные векторы](https://ru.wikipedia.org/wiki/%D0%A1%D0%BE%D0%B1%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80)
* По желанию:
    * [The evolution of trust](https://ncase.me/trust/) (занимает минут 30)
    * [The wisdom and/or madness of crowds](https://ncase.me/crowds/) (занимает минут 30)
    * я открыл в этом году издание [Pudding](https://pudding.cool/), там выходят статьи с красивой интерактивной визуализацией, основанной на реальных данных. Будет настроение --- взгляните.

## Домашнее задание (до 29.01.2019)
Домашнее задание нужно выполнять в отдельном `rmarkdown` файле. Получившийся файл следует помещать в соответствующую папку в своем репозитории на гитхабе. Более подробные инструкции [см. на этой странице](https://agricolamz.github.io/2019_data_analysis_for_linguists/index.html).

### 3.1
Выведите в консоль значение правдоподобия для нормального распределения $\mathcal{N}(\mu = 22,\, \sigma^{2}=6)$ при значениях, записанных в датасете про количество согласных.

### 3.2
[В датасет](https://raw.githubusercontent.com/agricolamz/2019_data_analysis_for_linguists/master/data/letter_frequency.csv) записаны частотности встречаемости букв разных языков. Проведите байесовский апдейт, используя в качестве данных слово "most" и считая, что все языки равновероятны. Выведите в консоль наибольшее апостериорную вероятность.

### 3.3
Проведите байесовский апдейт бета распредления, приведенного в датасете, при помощи априорного распредления Beta(33, 77) и приведите получившуюся долю успехов апостериорного распределения.