### Домашнее задание 5 (до 26.02.2019)
Домашнее задание нужно выполнять в отдельном `rmarkdown` файле. Получившийся файл следует помещать в соответствующую папку в своем репозитории на гитхабе. Более подробные инструкции [см. на этой странице](https://agricolamz.github.io/2019_data_analysis_for_linguists/index.html).

### 5.1
Скачайте датасет `chairs`, в котором собраны разные описания экземпляров из немецких он-лайн каталогов, отнесенным к категориям *Stuhl* 'стул' or *Sessel* 'кресло'. В датасете 19 переменных:

* `Shop` a factor that describes the online store with levels ikea.de, Moebel-Profi.de and roller.de.
* `WordDE` a factor that describes the specific lexical category.
* `Category` a factor that describes the more general lexical category (usually the last element of a composite noun), with levels Sessel and Stuhl.
* `Function` a factor with levels Eat, NotSpec, Outdoor, Relax and Work.
* `Age` a factor with levels Adult and Children.
* `Back` a factor with levels Adjust, High, Low and Mid.
* `Soft` a factor with levels No, Pad and Yes.
* `Arms` a factor with levels No and Yes.
* `Upholst` a factor with levels No and Yes.
* `MaterialSeat` a factor with levels Fabric, Leather, Loom_natur, Metal, Paper, Plastic, Polyamide, Rattan, Steel and Wood.
* `SeatHeight` a factor with levels Adjust, High and Norm.
* `SeatDepth` a factor with levels Adjust, Deep and Norm.
* `Swivel` a factor with levels No and Yes
* `Roll` a factor with levels No and Yes.
* `Rock` a factor with levels No and Rock.
* `AddFunctions` a factor with levels Bed, No and Table.
* `Recline` a factor with levels No and Yes.
* `ReclineBack` a factor with levels No and Yes.
* `SaveSpace` a factor with levels collapse, No and stack.

Используйте все переменные кроме переменных `Shop`, `WordDE` и `Category`, чтобы построить MCA. Нарисуйте все наблюдения, раскрасьте их по переменной `Category` и добавьте доверительные эллипсы. Сверху нанесите переменные из получившейся модели MCA. Получившийся график `ggplot` запустите в консоль.

### 5.2
Проанализируйте полученные результаты. Что Вы можете сказать на основе полученных результатов про категории `Stuhl` и `Sessel` в немецком? Что Вы можете сказать про переменные?

### 5.3

Cкачайте данные, содержащие 11 базовых цветов в разных подкорпусах  Corpus of Contemporary American English (Davies 2008 - ). Учитывались только адъективные употребления. Постройте CA и нарисуйте биплот с переменными из столбцов и строчек (без стрелочек). Получившийся график `ggplot` запустите в консоль.

### 5.4
Проинтерпретируйте полученные результаты.
